# Generated by Django 5.1.7 on 2025-03-27 02:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)], verbose_name='Широта')),
                ('longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)], verbose_name='Долгота')),
                ('height', models.IntegerField(verbose_name='Высота')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winter', models.CharField(blank=True, max_length=10, verbose_name='Зима')),
                ('summer', models.CharField(blank=True, max_length=10, verbose_name='Лето')),
                ('autumn', models.CharField(blank=True, max_length=10, verbose_name='Осень')),
                ('spring', models.CharField(blank=True, max_length=10, verbose_name='Весна')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fam', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('otc', models.CharField(max_length=150, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pereval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beauty_title', models.CharField(blank=True, max_length=255, verbose_name='Красивое название')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('other_titles', models.CharField(blank=True, max_length=255, verbose_name='Другие названия')),
                ('connect', models.TextField(blank=True, verbose_name='Что соединяет')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('status', models.CharField(choices=[('new', 'новый'), ('pending', 'модератор взял в работу'), ('accepted', 'модерация прошла успешно'), ('rejected', 'модерация прошла, информация не принята')], default='new', max_length=10, verbose_name='Статус')),
                ('coords', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mount_api.coords')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mount_api.level')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pereval', to='mount_api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.ImageField(upload_to='pereval_images/', verbose_name='Изображение')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('pereval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mount_api.pereval')),
            ],
        ),
    ]
